name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    
      - name: 🦑 Personal metrics (middle)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.github.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header

          # Templete
          template: classic
          
           # I Don't Know What Is This
          plugin_lines: yes
          
          # Most used languages
          plugin_languages: yes
          plugin_languages_ignored: dockerfile, batchfile, makefile, qmake, lex, cmake, gnuplot, vue
          plugin_languages_details: lines, percentage
          plugin_languages_limit: 10
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes
          
          # Notable
          plugin_notable: yes
          plugin_notable_repositories: no

          # Achievements
          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_achievements_display: compact
          plugin_achievements_limit: 0 
          
          # Order
          config_order: base.header, lines, languages, notable, topics, achievements
